name: GoLang

on:
  push:
    branches:
    - v[0-9]+.[0-9]+
    

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
    # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "DipSA55 CI/CD Assignment Submission"
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Name:*\n Gao Yumengdie"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Metriculation:*\n A0265061L"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Email:*\n e1045736@u.nus.edu"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Repositary:*\n ${{ github.repositoryUrl }}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Delopyment:*\n https://golangdeploy-production.up.railway.app/"
                        }
                    ]
                },
                {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*<https://golangdeploy-production.up.railway.app/|Open Application>*"
                    }
                }
            ]

          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL1 }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    
    - name: Railway CLI Create
      run: npm i -g @railway/cli
    
    - name: Railway Auto deploy 
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAIL_WAY }}
        
      
      
