name: Release and Deploy Golang

on:
  push:
    branches:
    - "v<digit>.<digit>"
    - "!v*.*.*"
    - "!v*.*-beta"


jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    #- name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
    # For posting a rich message using Block Kit
        #payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "DipSA55 CI/CD Assignment Submission",
                        "emoji": true
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Name:*\n Zhao Tong"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Metriculation:*\nA0265362A"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Email:*\ne1061635@u.nus.edu"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Repositary:*\nhttps://github.com/TaraZhao777/Golang.git"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Delopyment:*\nhttps://golang-production-96ca.up.railway.app/"
                        }
                    ]
                },
                {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "<https://golang-production-96ca.up.railway.app/|Open Application>"
                    }
                }
            ]

          }
      #env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK